### ISSUE TITLE
include xxx.ejs时报错

### ISSUE THREAD

**Issue by soneway** [whxaxes/gulp-include-html#1]
如题,在html里只是想include一段模板,但是会报错

**Comment by whxaxes** [comment]
能贴一下错误信息吗？

**Comment by soneway** [comment]
file is not exist：d:/xampp/htdocs/pc/src/html/tmpl/home/enterprise.ejs.html

**Comment by soneway** [comment]
不过之前报错不是这样...是报模板文件里xxx.ejs里变量未定义的错

**Comment by whxaxes** [comment]
第一个问题，是因为我处理的问题，因为我会自动给没有.html后缀的文件加上.html后缀，所以加上了.html后文件就找不到了，解决办法就你在options里传入一个suffix:'ejs'的参数，因为组件默认的后缀名是html

第二个的原因是ejs本身的问题，ejs不允许一个未定义的变量被使用，也就是你写的时候得在头部加上变量的定义比如：

```
<% var args = args || null;  %>
```

才能正常使用

不过ejs确实比较坑，之后我会抽点时间写一个基于nunjucks的include组件，用起来应该会更好一些，nunjucks就不会有这个问题了

**Comment by soneway** [comment]
恩,暂时只能这样了,看了好多include插件,有的没有baseDir这个功能,有的设置了baseDir又只能按baseDir寻址

**Comment by whxaxes** [comment]
嗯，我也是没看到适用的include插件才自己写一个的
