### ISSUE TITLE
监听全部 html 文件时并传递参数会报错

### ISSUE THREAD

**Issue by cobish** [whxaxes/gulp-include-html#2]
由于需要监听到每个 html 文件改动并执行 include html 操作，所以我监听了所有的 html 文件。

``` js
var gulp = require('gulp');
var include = require('gulp-include-html');

var files = './src/**/*.html';

gulp.task('include', function() {
  return gulp.src(files)
    .pipe(include())
    .pipe(gulp.dest('./dist'));
});

gulp.task('watch', function() {
  gulp.watch(files, ['include']);
});
```

但是我在 html 中传递了参数，代码如下：

index.html

``` html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>demo</title>
</head>
<body>
  @@include('./test/header.html', {
    contents: 'wabish'
  });
</body>
</html>
```

test/header.html

``` html
<ul>
  <li>gulp</li>
  <li>grunt</li>
  <li><%= contents %></li>
</ul>
```

此时 console 会报参数没找到的错误：

![qq 20161205141901](https://cloud.githubusercontent.com/assets/8475099/20875424/af4133d4-baf5-11e6-80ae-35ab45ad76b5.png)

请问你是否有遇到此问题并解决？

**Comment by whxaxes** [comment]
此前用的时候没遇到过这种问题，我待会试一下

**Comment by cobish** [comment]
@whxaxes 好的，谢谢

**Comment by whxaxes** [comment]
看了一下代码，发现代码在处理include逻辑的时候确实有点问题，刚发了一个 patch 版本 1.0.13，你更新一下看一下你的这个问题有没有被修复

**Comment by cobish** [comment]
好的，感谢反馈，明天我试试

**Comment by cobish** [comment]
@whxaxes 你好，我今天试了一下还是原来的例子，发现还是会有跟原来一样的报错。

**Comment by whxaxes** [comment]
方便把例子demo打个包发到我邮箱吗？

**Comment by cobish** [comment]
@whxaxes 邮件已经发了，麻烦你了

**Comment by whxaxes** [comment]
hi，你只需要把`header.html`重命名为`_header.html`即可，而且那个报错也不会影响编译的，因为你用了**/*，所以组件也去处理 header.html了，但是 header.html 里面有模板语法，所以会解析失败，文件名前面加个`_`，组件就不会去管那个文件了。没必要为了这些文件多一次正则匹配，所以我把 pull request 关掉了哈

**Comment by cobish** [comment]
@whxaxes 加了下划线可以了，阿里嘎多！
